source = Background.java Clock.java Direction.java DunkAProf.java \
	GamePanel.java Location.java MediaPlayer.java Paused.java \
	Person.java Pool.java Projectile.java Score.java \
	Slider.java Animation.java

classes = Background.class Clock.class Direction.class DunkAProf.class \
	GamePanel.class Location.class MediaPlayer.class Paused.class \
	Person.class Pool.class Projectile.class Score.class \
	Slider.class Animation.class
	

$(classes) : $(source)
	javac $(source)

.PHONY : clean
clean :
	rm *.class
